# Generated by Django 6.0.3 on 2026-05-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('buscar_ativos', 'Buscar Ativos'), ('scrap', 'Scrap Cotas')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('done', 'Concluído'), ('error', 'Erro')], default='running', max_length=10)),
                ('detalhe', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FI', 'FI'), ('FII', 'FII'), ('ACAO', 'ACAO'), ('INDICE', 'INDICE'), ('RENDA_FIXA', 'RENDA_FIXA')], max_length=20)),
                ('id_quantum', models.CharField(max_length=100)),
                ('subtipo', models.CharField(blank=True, default='', max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('ticker', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('setor', models.CharField(blank=True, default='', max_length=120)),
                ('gestora', models.CharField(blank=True, default='', max_length=200)),
                ('primeira_cota', models.DateField(blank=True, null=True)),
                ('metadados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'id_quantum'), name='ativo_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='CotacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('valor', models.FloatField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='scrapper.ativo')),
            ],
            options={
                'verbose_name': 'Cotação Diária',
                'verbose_name_plural': 'Cotações Diárias',
                'ordering': ['data'],
                'unique_together': {('ativo', 'data')},
            },
        ),
    ]
