# Generated by Django 6.0.3 on 2026-03-16 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('buscar_ativos', 'Buscar Ativos'), ('scrap', 'Scrap Cotas')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('done', 'Concluído'), ('error', 'Erro')], default='running', max_length=10)),
                ('detalhe', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtivoQuantum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_quantum', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('primeira_cota', models.DateField(blank=True, null=True)),
                ('gestora', models.CharField(blank=True, max_length=200)),
                ('dados_complementares', models.JSONField(default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantum', to='scrapper.ativo')),
            ],
            options={
                'verbose_name': 'Ativo Quantum',
                'verbose_name_plural': 'Ativos Quantum',
            },
        ),
    ]
