# Generated by Django 6.0.3 on 2026-05-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_seed_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteiraFundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('importada_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteiras', to='scrapper.ativo')),
            ],
            options={
                'verbose_name': 'Carteira de Fundo',
                'verbose_name_plural': 'Carteiras de Fundo',
                'ordering': ['-competencia'],
            },
        ),
        migrations.CreateModel(
            name='PosicaoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('participacao', models.FloatField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='scrapper.carteirafundo')),
            ],
            options={
                'verbose_name': 'Posição da Carteira',
                'verbose_name_plural': 'Posições da Carteira',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='carteirafundo',
            constraint=models.UniqueConstraint(fields=('ativo', 'competencia'), name='carteira_ativo_competencia'),
        ),
    ]
