# Generated by Django 6.0.3 on 2026-03-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_cotacaodiaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacaodiaria',
            options={'ordering': ['data'], 'verbose_name': 'Cotação Diária', 'verbose_name_plural': 'Cotações Diárias'},
        ),
    ]
