# Generated by Django 6.0.3 on 2026-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_carteirafundo_posicaocarteira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteirafundo',
            name='agregacoes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='posicaocarteira',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
