# Generated by Django 6.0.3 on 2026-05-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_carteirafundo_agregacoes_posicaocarteira_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tipo',
            field=models.CharField(choices=[('buscar_ativos', 'Buscar Ativos'), ('scrap', 'Scrap Cotas'), ('carteira', 'Sincronizar Carteira')], max_length=20),
        ),
    ]
