# Generated by Django 6.0.3 on 2026-05-28 22:41

from decimal import Decimal, localcontext

from django.db import migrations, models


def _backfill_retornos(apps, schema_editor):
    Ativo = apps.get_model("scrapper", "Ativo")
    CotacaoDiaria = apps.get_model("scrapper", "CotacaoDiaria")
    for ativo_id in Ativo.objects.values_list("id", flat=True):
        cotacoes = list(
            CotacaoDiaria.objects.filter(ativo_id=ativo_id).order_by("data")
        )
        if not cotacoes:
            continue
        anterior = None
        with localcontext() as ctx:
            ctx.prec = 50
            for cotacao in cotacoes:
                if anterior is None or anterior == 0:
                    cotacao.retorno = Decimal(0)
                    cotacao.retorno_ln = Decimal(0)
                else:
                    razao = cotacao.valor / anterior
                    cotacao.retorno = razao - 1
                    cotacao.retorno_ln = razao.ln()
                anterior = cotacao.valor
        CotacaoDiaria.objects.bulk_update(cotacoes, ["retorno", "retorno_ln"], batch_size=500)


def _noop(apps, schema_editor):
    # Reversão derruba as colunas (AddField reverso); a perda dos retornos no
    # rollback é aceitável — eles são recomputáveis a partir de `valor`.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_alter_job_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaodiaria',
            name='retorno',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cotacaodiaria',
            name='retorno_ln',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cotacaodiaria',
            name='valor',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.RunPython(_backfill_retornos, _noop),
    ]
