# Generated by Django 6.0.3 on 2026-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_alter_job_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacaodiaria',
            name='retorno',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cotacaodiaria',
            name='retorno_ln',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cotacaodiaria',
            name='valor',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
